name: cipherlabz_app

packages:
  - apps/**
  - packages/**

scripts:
  build:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 4

# scripts:
#   generate:
#     run: melos exec -c 1 --depends-on build_runner -- dart run build_runner build
