name: cipherlabz_app
publish_to: none
environment:
  sdk: ^3.8.0

dependencies: 
  intl: ^0.18.1
  location: ^5.0.0
  google_maps_flutter: ^2.5.0
  flutter_swipe_button: ^2.1.1+1
  
  cupertino_icons: ^1.0.8
  local_auth: ^2.3.0  

dev_dependencies:
  build_runner: ^2.4.6
  melos: 6.3.3
  flutter_lints: ^5.0.0

