name: login_package
description: A new Flutter package project.
version: 0.0.1
publish_to: none
environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5
  flutter_svg: ^2.0.7
  dartz: ^0.10.1
  shared_preferences: ^2.5.3
  intl: ^0.18.1
  flutter_riverpod: ^2.6.1
  color_package:
    path: ../../packages/color_package
  shared_resources:
    path: ../../packages/shared_resources
  core:
    path: ../../packages/core
  splash:
    path: ../../packages/splash
  user_package:
    path: ../../packages/user_package
  attendance_package:
    path: ../../packages/attendance_package
  home_package:
    path: ../../packages/home_package
  leave_package:
    path: ../../packages/leave_package
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  assets:
    - assets/login_page_img.png
