name: shared_resources
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  fonts:
      - family: Poppins
        fonts:
          - asset: assets/fonts/Poppins-Thin100.ttf
            weight: 100
          - asset: assets/fonts/Poppins-Regular400.ttf
            weight: 400
          - asset: assets/fonts/Poppins-Medium500.ttf
            weight: 500
          - asset: assets/fonts/Poppins-SemiBold600.ttf
            weight: 600
          - asset: assets/fonts/Poppins-Bold700.ttf
            weight: 700
          
      - family: Inter
        fonts:
          - asset: assets/fonts/Inter_18pt-Medium.ttf
            weight: 500

      - family: Londrina Solid
        fonts:
          - asset: assets/fonts/LondrinaSolid-Regular.ttf
            weight: 400
  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/icons/

  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
